#!/usr/bin/env sh
#
# Formats AWK programs

set -eu

format(){
	sed 's/^[\t ]*$/#~#~#/g' "$1" | gawk -o- -f- | sed 's/#~#~#//g' | cat -s
}

usage() {
	printf 'usage: %s [flags] [path ...]
	-w  write result to (source) file instead of stdout\n' "$(basename "$0")"
	exit 1
}

while getopts "dhw" c; do
	case "$c" in
	d) set -x ;;
	w) inplace=true ;;
	*) usage ;;
	esac
done
shift "$((OPTIND - 1))"

in="${1--}"
: "${inplace=false}"

if "$inplace"; then
	[ "$in" = "-" ] && 
		echo 'error: cannot use -w with standard in' >&2 &&
		exit 1

	out="$(mktemp)"
	trap 'rm -f "$out"' EXIT
fi

: "${out=-}"

if "$inplace"; then
       format "$in" > "$out"
       cp "$out" "$in"
else
       format "$in"
fi

