#!/bin/sh

lint() {
	gawk --posix "--lint$fatal" -f "$1"  >/dev/null || status="$?"

	# gawk returns 2 if there is errors
	[ "$status" = 2 ] && return 1 || return 0
}

link() {
	awk '
		/^#include/ {
			gsub(/"/, "", $2)

			cmd = "[ -f " $2 " ]"

			exists = system(cmd)
			close(cmd)

			if ( exists == 1 ) {
				print "sawk: could not find include: " $2 > "/dev/stderr"
				exit
			}

			while ((getline x < $2) > 0) print x
			next
		}

		{ print }
		
		END { exit exists }
	' "$@" 
}

# usage() {
# 	cat << 'EOF' >&2
# usage: sawk [-dmv] [file]
# 
# See 'man sawk' for more info.
# EOF
# 	exit 1
# }

set -eu

fatal="=fatal"
while getopts "mo:" c; do
	case "$c" in
	m) fatal="" ;;
	o) out="$OPTARG" ;;
	*) return 1 ;;
	esac
done
shift $((OPTIND - 1))

[ "$#" -ne 1 ] && return 1

: "${out=a.out}"

linked="$(mktemp)"
trap 'rm -f $linked' EXIT

link "$1" > "$linked"

lint "$linked"

awka -X -f "$linked"
rm -f awka_out.c
mv awka.out "$out"

