#!/bin/sh

format(){
	# we want to protect single empty lines
	sed 's/^[\t ]*$/#~#~#/g' | gawk -o- -f- | sed 's/#~#~#//g' | cat -s
}

lint() {
	gawk --posix "--lint$fatal" -f "${1--}" >/dev/null
}

wrap(){
	file="$1"
	shift

	{
		echo "#!/usr/bin/env sh"
		echo "exec awk '"
		cat -
		echo "'"' -- "$@"'
	} > "${file%.*}"

	echo "${file%.*}"
}

link() {
	awk '
		/^#include/ {
			gsub(/"/, "", $2)

			cmd = "[ -f " $2 " ]"

			exists = system(cmd)
			close(cmd)

			if ( exists == 1 ) {
				print "sawk: could not find include: " $2 > "/dev/stderr"
				exit
			}

			while ((getline x < $2) > 0)
				print x
			next
		}

		{
			print
		}
		
		END {
			exit exists
		}
	' "$@" 
}

usage() {
	{
		echo "usage: sawk [-dmv] [file]"
		echo
		echo "See 'man sawk' for more info."
	} >&2
	exit 1
}

set -eu

fatal="=fatal"
while getopts "mv" c; do
	case "$c" in
	d) set -x ;;
	m) fatal="" ;;
	v) echo "sawk v0.0.1" && exit ;;
	*) usage ;;
	esac
done
shift $((OPTIND - 1))

[ "$#" -ne 1 ] && usage

linked="$(link "$1")"

echo "$linked" | lint -

out="${1%.*}"

echo "$linked" | format | wrap > "$out"
chmod +x "$out"
echo "$out"

