#!/bin/sh

run_usage() {
	cat <<'EOF' >&2
usage: sawk run program [arguments...]

Run compiles and runs the named awk program.
EOF
	exit 1
}

set -eu

[ "$#" -eq 0 ] && run_usage

TMP="$(mktemp)"
trap 'rm -f $TMP' EXIT

./sawk-build -o "$TMP" "$1"

"$TMP" "$@"
